### ISSUE TITLE
'transactionReceipt' is deprecated: first deprecated in iOS 7.0 - Use -[NSBundle appStoreReceiptURL]

### ISSUE THREAD

**Issue by Jules2010** [evands/iap_validation#23]
/Pods/IAPValidation/RRTransactionVerifier.m: 'transactionReceipt' is deprecated: first deprecated in iOS 7.0 - Use -[NSBundle appStoreReceiptURL]

Getting three warning for this, I'm not sure how to workaround this.
I don't want to have to re-write my iap functionality.

Suggestions?

Thanks,

Jules.

**Comment by evands** [comment]
As noted in the readme, iap_validation has no roll in iOS 6.x and later.  I'm going to hide the repository, in fact, as I don't think anyone is still building new code for iOS 5.
